export default {
  login: "xxxmarxxx",
  id: 50579679,
  node_id: "MDQ6VXNlcjUwNTc5Njc5",
  avatar_url: "https://avatars.githubusercontent.com/u/50579679?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/xxxmarxxx",
  html_url: "https://github.com/xxxmarxxx",
  followers_url: "https://api.github.com/users/xxxmarxxx/followers",
  following_url: "https://api.github.com/users/xxxmarxxx/following{/other_user}",
  gists_url: "https://api.github.com/users/xxxmarxxx/gists{/gist_id}",
  starred_url: "https://api.github.com/users/xxxmarxxx/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/xxxmarxxx/subscriptions",
  organizations_url: "https://api.github.com/users/xxxmarxxx/orgs",
  repos_url: "https://api.github.com/users/xxxmarxxx/repos",
  events_url: "https://api.github.com/users/xxxmarxxx/events{/privacy}",
  received_events_url: "https://api.github.com/users/xxxmarxxx/received_events",
  type: "User",
  site_admin: false,
  name: "Mariusz",
  company: 'coding',
  blog: "www.mariuszbrainard.de",
  location: "Berlin",
  email: null,
  hireable: null,
  bio: "< Web-Developer in education /> /!-- HTML - CSS - JavaScript - React --/>",
  twitter_username: 'mariusz',
  public_repos: 18,
  public_gists: 0,
  followers: 5,
  following: 3,
  created_at: "2019-05-13T11:09:51Z",
  updated_at: "2021-01-25T17:17:11Z"
  }

