export default [
    {
        login: "KajnCode",
        id: 55787638,
        node_id: "MDQ6VXNlcjU1Nzg3NjM4",
        avatar_url: "https://avatars.githubusercontent.com/u/55787638?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/KajnCode",
        html_url: "https://github.com/KajnCode",
        followers_url: "https://api.github.com/users/KajnCode/followers",
        following_url: "https://api.github.com/users/KajnCode/following{/other_user}",
        gists_url: "https://api.github.com/users/KajnCode/gists{/gist_id}",
        starred_url: "https://api.github.com/users/KajnCode/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/KajnCode/subscriptions",
        organizations_url: "https://api.github.com/users/KajnCode/orgs",
        repos_url: "https://api.github.com/users/KajnCode/repos",
        events_url: "https://api.github.com/users/KajnCode/events{/privacy}",
        received_events_url: "https://api.github.com/users/KajnCode/received_events",
        type: "User",
        site_admin: false
        },
        {
        login: "gael-src",
        id: 55788820,
        node_id: "MDQ6VXNlcjU1Nzg4ODIw",
        avatar_url: "https://avatars.githubusercontent.com/u/55788820?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/gael-src",
        html_url: "https://github.com/gael-src",
        followers_url: "https://api.github.com/users/gael-src/followers",
        following_url: "https://api.github.com/users/gael-src/following{/other_user}",
        gists_url: "https://api.github.com/users/gael-src/gists{/gist_id}",
        starred_url: "https://api.github.com/users/gael-src/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/gael-src/subscriptions",
        organizations_url: "https://api.github.com/users/gael-src/orgs",
        repos_url: "https://api.github.com/users/gael-src/repos",
        events_url: "https://api.github.com/users/gael-src/events{/privacy}",
        received_events_url: "https://api.github.com/users/gael-src/received_events",
        type: "User",
        site_admin: false
        },
        {
        login: "victoria2266",
        id: 54753921,
        node_id: "MDQ6VXNlcjU0NzUzOTIx",
        avatar_url: "https://avatars.githubusercontent.com/u/54753921?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/victoria2266",
        html_url: "https://github.com/victoria2266",
        followers_url: "https://api.github.com/users/victoria2266/followers",
        following_url: "https://api.github.com/users/victoria2266/following{/other_user}",
        gists_url: "https://api.github.com/users/victoria2266/gists{/gist_id}",
        starred_url: "https://api.github.com/users/victoria2266/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/victoria2266/subscriptions",
        organizations_url: "https://api.github.com/users/victoria2266/orgs",
        repos_url: "https://api.github.com/users/victoria2266/repos",
        events_url: "https://api.github.com/users/victoria2266/events{/privacy}",
        received_events_url: "https://api.github.com/users/victoria2266/received_events",
        type: "User",
        site_admin: false
        },
        {
        login: "Kuohamkun",
        id: 50623506,
        node_id: "MDQ6VXNlcjUwNjIzNTA2",
        avatar_url: "https://avatars.githubusercontent.com/u/50623506?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/Kuohamkun",
        html_url: "https://github.com/Kuohamkun",
        followers_url: "https://api.github.com/users/Kuohamkun/followers",
        following_url: "https://api.github.com/users/Kuohamkun/following{/other_user}",
        gists_url: "https://api.github.com/users/Kuohamkun/gists{/gist_id}",
        starred_url: "https://api.github.com/users/Kuohamkun/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/Kuohamkun/subscriptions",
        organizations_url: "https://api.github.com/users/Kuohamkun/orgs",
        repos_url: "https://api.github.com/users/Kuohamkun/repos",
        events_url: "https://api.github.com/users/Kuohamkun/events{/privacy}",
        received_events_url: "https://api.github.com/users/Kuohamkun/received_events",
        type: "User",
        site_admin: false
        },
        {
        login: "CharlesCreativeContent",
        id: 62077627,
        node_id: "MDQ6VXNlcjYyMDc3NjI3",
        avatar_url: "https://avatars.githubusercontent.com/u/62077627?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/CharlesCreativeContent",
        html_url: "https://github.com/CharlesCreativeContent",
        followers_url: "https://api.github.com/users/CharlesCreativeContent/followers",
        following_url: "https://api.github.com/users/CharlesCreativeContent/following{/other_user}",
        gists_url: "https://api.github.com/users/CharlesCreativeContent/gists{/gist_id}",
        starred_url: "https://api.github.com/users/CharlesCreativeContent/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/CharlesCreativeContent/subscriptions",
        organizations_url: "https://api.github.com/users/CharlesCreativeContent/orgs",
        repos_url: "https://api.github.com/users/CharlesCreativeContent/repos",
        events_url: "https://api.github.com/users/CharlesCreativeContent/events{/privacy}",
        received_events_url: "https://api.github.com/users/CharlesCreativeContent/received_events",
        type: "User",
        site_admin: false
        }


]